#!/bin/bash

cd

apt-get -y  install git build-essential cmake libuv1-dev libmicrohttpd-dev software-properties-common;
add-apt-repository -y ppa:jonathonf/gcc-7.1;
apt-get -y  update;

echo 10000 > /proc/sys/vm/nr_hugepages

fallocate -l 4G /swapfile
chmod 600 /swapfile
mkswap /swapfile
swapon /swapfile
echo /swapfile > none    swap    sw    0   0 /etc/fstab
echo vm.swappiness=10 > /etc/sysctl.conf
sysctl -p

apt-get -y  install gcc-7 g++-7;
git clone https://github.com/xmrig/xmrig.git

cd xmrig
mkdir build
cd build

cmake .. -DCMAKE_C_COMPILER=gcc-7 -DCMAKE_CXX_COMPILER=g++-7
make

./xmrig -a cryptonight -o stratum+tcp://xmr.pool.minergate.com:45700 -u ipnualpri123@gmail.com -p x
